grpc.client.order-service.address: static://localhost:9090
grpc.client.order-service.negotiation-type: plaintext

grpc.client.notification-service.address: static://localhost:9091
grpc.client.notification-service.negotiation-type: plaintext

server.port: 8081